import type { Metadata } from "next";

// Styles
import "../styles/styles.scss"

// Components
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="header-container">
          <Header />
        </div>
        <div className="website-content-container">
          {children}
        </div>
        <div className="footer-container">
          <p>© 2024 My Website</p>
        </div>
      </body>
    </html>
  );
}
